## NumPy

## single dimensional array

In [2]:
import numpy as np

In [11]:
from matplotlib import pyplot as plt

In [3]:
n1=np.array([10,20,30,40,50])

In [4]:
n1

array([10, 20, 30, 40, 50])

In [5]:
type(n1)

numpy.ndarray

## multi dimensional array

In [4]:
n2=np.array([[2,4,6,8,10],[3,6,9,12,15]])

In [5]:
n2

array([[ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])

In [6]:
type(n2)

numpy.ndarray

## Initializing NumPy array with zeros

In [20]:
n3=np.zeros([1,2])

In [21]:
n3

array([[0., 0.]])

In [15]:
n4=np.zeros([5,6])

In [16]:
n4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## Initialize NumPy array with the same number

In [22]:
n5=np.full([5,7],10)

In [23]:
n5

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

## Initializing NumPy array within a range

In [27]:
n6=np.arange(10,30)

In [28]:
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [29]:
n7=np.arange(10,30,5)

In [30]:
n7

array([10, 15, 20, 25])

## Initializing NumPy array with random numbers

In [31]:
n8=np.random.randint(10,100)

In [32]:
n8

71

In [35]:
n9=np.random.randint(10,100,9)#choose 9 random numbers between 10 & 100

In [36]:
n9

array([83, 60, 67, 94, 58, 33, 54, 48, 62])

## Checking the shape of NumPy arrays

In [37]:
n10=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [38]:
n10.shape

(2, 5)

In [39]:
n10.shape=(5,2)

In [40]:
n10

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

## Addition of NumPy arrays

In [41]:
n11=np.array([5,10,15,20,25,30])
n12=np.array([10,20,30,40,50,60])
np.sum([n11,n12])

315

In [45]:
np.sum([n11,n12],axis=0)

array([15, 30, 45, 60, 75, 90])

In [46]:
np.sum([n11,n12],axis=1)#r1=rows#########

array([105, 210])

## vstack(),hstack() & column_stack() methods

In [47]:
n13=np.array([10,20,30,40,50])
n14=np.array([60,70,80,90,100])

In [48]:
np.vstack([n13,n14])

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [49]:
np.hstack([n13,n14])

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [50]:
np.column_stack([n13,n14])

array([[ 10,  60],
       [ 20,  70],
       [ 30,  80],
       [ 40,  90],
       [ 50, 100]])